apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nodejs-template
  title: Create a Node.js Service
  description: A template to create a simple Node.js service using Express. 
spec:
  owner: guest #khai bao template nay thuoc ve khuon mau cua ai
  type: service
  parameters:
    - title: Basic Information
      description: Provide basic information about your project
      required: [name, owner]
      properties:
        name:
          title: Name
          type: string
          description: Unique name of your project
        owner:
          title: Owner
          type: string 
          description: GitHub username or team that will own the repository
  ...
  steps:
    - id: fetchBase
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: Project ${{ parameters.name }} auto-generated by IDP GenAI
        repoUrl: github.com?owner=goldenpoppy-study&repo=${{ parameters.name }}
    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'